### ISSUE TITLE
Intuitive understanding of RPS

### ISSUE THREAD

**Issue by oliverangelil** [TheClimateCorporation/properscoring#4]
I thought the RPS is the area of the shaded parts of the ECDFs (see attached). The shaded area of the red curve looks to be larger than the shaded area of the blue curve, yet the RPS value of the red is lower than the blue (the black is observations and the two colours are two different forecasts). Does anyone have an intuitive (non-mathematical) explanation of what RPS actually is?

![rpss_dummy](https://user-images.githubusercontent.com/15682787/36004545-52fd1f8a-0d87-11e8-9ce2-109317f185f1.png)

**Comment by shoyer** [comment]
RPS is related to the shaded part of the ECDF, but it's actually the integral of the *squared* difference, not the integral of the absolute difference.

I don't know if the integral of the absolute difference is a proper scoring rule, but I suspect it is not.

**Comment by oliverangelil** [comment]
Ah okay. So it's the sum of the vertical distances squared. That's why RPS for blue could be higher than for red, because the vertical distance for the blue are at times almost 100, but for red the max is ~60.

**Comment by shoyer** [comment]
@oliverangelil Yes, exactly.
