### ISSUE TITLE
Link for CRPS broken

### ISSUE THREAD

**Issue by jlandmann** [TheClimateCorporation/properscoring#9]
The following link in `README.rst`:

    .. _Continuous Ranked Probability Score: http://www.eumetcal.org/resources/ukmeteocal/verification/www/english/msg/ver_prob_forec/uos3b/uos3b_ko1.htm

doesn't seem to be working anymore. My search for the somewhat cryptic page name was not successful, unfortunately. Does anybody know under which new URL this page has ended up?

**Comment by hcvazquez** [comment]
Hi @jlandmann, I really don't know. However, I found the page in the web archives. 

https://web.archive.org/web/20161102094610/http://www.eumetcal.org/resources/ukmeteocal/verification/www/english/msg/ver_prob_forec/uos3b/uos3b_ko1.htm

**Comment by jlandmann** [comment]
Okay, very cool, thanks! I didn't know that tese kind of webpages exist ;-)

**Comment by shoyer** [comment]
Thanks for the pull request!
